<a href="https://colab.research.google.com/github/kenny08gt/Richter-s-Predictor-Modeling-Earthquake-Damage-DS/blob/main/Richter's_Predictor_Modeling_Earthquake_Damage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

We're trying to predict the ordinal variable damage_grade, which represents a level of damage to the building that was hit by the earthquake. There are 3 grades of the damage:

1 represents low damage
2 represents a medium amount of damage
3 represents almost complete destruction

In [22]:
import pandas as pd 

#building_id,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,has_superstructure_adobe_mud,has_superstructure_mud_mortar_stone,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
df = pd.read_csv("/content/drive/MyDrive/Data science/DataDriven/Richters predictor/train_values.csv")
labels = pd.read_csv("/content/drive/MyDrive/Data science/DataDriven/Richters predictor/train_labels.csv")
df = pd.merge(df, labels, on=['building_id'])

print(df.head(10))

   building_id  geo_level_1_id  ...  has_secondary_use_other  damage_grade
0       802906               6  ...                        0             3
1        28830               8  ...                        0             2
2        94947              21  ...                        0             3
3       590882              22  ...                        0             2
4       201944              11  ...                        0             3
5       333020               8  ...                        0             2
6       728451               9  ...                        0             3
7       475515              20  ...                        0             1
8       441126               0  ...                        0             2
9       989500              26  ...                        0             1

[10 rows x 40 columns]


In [39]:
df.dtypes

building_id                                int64
geo_level_1_id                             int64
geo_level_2_id                             int64
geo_level_3_id                             int64
count_floors_pre_eq                        int64
age                                        int64
area_percentage                            int64
height_percentage                          int64
land_surface_condition                    object
foundation_type                           object
roof_type                                 object
ground_floor_type                         object
other_floor_type                          object
position                                  object
plan_configuration                        object
has_superstructure_adobe_mud               int64
has_superstructure_mud_mortar_stone        int64
has_superstructure_stone_flag              int64
has_superstructure_cement_mortar_stone     int64
has_superstructure_mud_mortar_brick        int64
has_superstructure_c

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260601 entries, 0 to 260600
Data columns (total 40 columns):
 #   Column                                  Non-Null Count   Dtype 
---  ------                                  --------------   ----- 
 0   building_id                             260601 non-null  int64 
 1   geo_level_1_id                          260601 non-null  int64 
 2   geo_level_2_id                          260601 non-null  int64 
 3   geo_level_3_id                          260601 non-null  int64 
 4   count_floors_pre_eq                     260601 non-null  int64 
 5   age                                     260601 non-null  int64 
 6   area_percentage                         260601 non-null  int64 
 7   height_percentage                       260601 non-null  int64 
 8   land_surface_condition                  260601 non-null  object
 9   foundation_type                         260601 non-null  object
 10  roof_type                               260601 non-null 

In [12]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm', axis=None)

There seems to be no directly correlated variable with damage



In [23]:
df.describe()


building_id  geo_level_1_id  ...  has_secondary_use_other   damage_grade
count  2.606010e+05   260601.000000  ...            260601.000000  260601.000000
mean   5.256755e+05       13.900353  ...                 0.005119       2.238272
std    3.045450e+05        8.033617  ...                 0.071364       0.611814
min    4.000000e+00        0.000000  ...                 0.000000       1.000000
25%    2.611900e+05        7.000000  ...                 0.000000       2.000000
50%    5.257570e+05       12.000000  ...                 0.000000       2.000000
75%    7.897620e+05       21.000000  ...                 0.000000       3.000000
max    1.052934e+06       30.000000  ...                 1.000000       3.000000

[8 rows x 32 columns]

In [59]:
training_data = df.copy()
del training_data['building_id']
del training_data['geo_level_3_id']
del training_data['has_secondary_use_health_post']
del training_data['has_secondary_use_gov_office']
del training_data['has_secondary_use_use_police']
del training_data['has_secondary_use_other']

training_data["geo_level_1_id"] /= 30
training_data['geo_level_2_id'] /= 1427
training_data['count_floors_pre_eq'] /= 9
training_data['age'] /= 995
training_data['area_percentage'] /= 100
training_data['height_percentage'] /= 32
#n, o, t.
training_data['land_surface_condition'] = training_data['land_surface_condition'].str.replace('n', '0').str.replace('o', '1').str.replace('t', '2')
training_data['land_surface_condition'] = pd.to_numeric(training_data['land_surface_condition'], errors='coerce').astype('Int64')
#n, q, x.
training_data['roof_type'] = training_data['roof_type'].str.replace('n', '0').str.replace('q', '1').str.replace('x', '2')
training_data['roof_type'] = pd.to_numeric(training_data['roof_type'], errors='coerce').astype('Int64')
#h, i, r, u, w
training_data['foundation_type'] = training_data['foundation_type'].str.replace('h', '0').str.replace('i', '1').str.replace('r', '2').str.replace('u', '3').str.replace('w', '4')
training_data['foundation_type'] = pd.to_numeric(training_data['foundation_type'], errors='coerce').astype('Int64')
#f, m, v, x, z.
training_data['ground_floor_type'] = training_data['ground_floor_type'].str.replace('f', '0').str.replace('m', '1').str.replace('v', '2').str.replace('x', '3').str.replace('z', '4')
training_data['ground_floor_type'] = pd.to_numeric(training_data['ground_floor_type'], errors='coerce').astype('Int64')
#j, q, s, x.
training_data['other_floor_type'] = training_data['other_floor_type'].str.replace('j', '0').str.replace('q', '1').str.replace('s', '2').str.replace('x', '3')
training_data['other_floor_type'] = pd.to_numeric(training_data['other_floor_type'], errors='coerce').astype('Int64')
#j, o, s, t.
training_data['position'] = training_data['position'].str.replace('j', '0').str.replace('o', '1').str.replace('s', '2').str.replace('t', '3')
training_data['position'] = pd.to_numeric(training_data['position'], errors='coerce').astype('Int64')
#a, c, d, f, m, n, o, q, s, u.
training_data['plan_configuration'] = training_data['plan_configuration'].str.replace('a', '0').str.replace('c', '1').str.replace('d', '2').str.replace('f', '3').str.replace('m', '4').str.replace('n', '5').str.replace('o', '6').str.replace('q', '7').str.replace('s', '8').str.replace('u', '9')
training_data['plan_configuration'] = pd.to_numeric(training_data['plan_configuration'], errors='coerce').astype('Int64')
#a, r, v, w.
training_data['legal_ownership_status'] = training_data['legal_ownership_status'].str.replace('a', '0').str.replace('r', '1').str.replace('v', '2').str.replace('w', '3')
training_data['legal_ownership_status'] = pd.to_numeric(training_data['legal_ownership_status'], errors='coerce').astype('Int64')


training_data['count_families'] /= 9
training_data.describe()

geo_level_1_id  ...   damage_grade
count   260601.000000  ...  260601.000000
mean         0.463345  ...       2.238272
std          0.267787  ...       0.611814
min          0.000000  ...       1.000000
25%          0.233333  ...       2.000000
50%          0.400000  ...       2.000000
75%          0.700000  ...       3.000000
max          1.000000  ...       3.000000

[8 rows x 34 columns]

In [60]:
training_data.dtypes

geo_level_1_id                            float64
geo_level_2_id                            float64
count_floors_pre_eq                       float64
age                                       float64
area_percentage                           float64
height_percentage                         float64
land_surface_condition                      Int64
foundation_type                             Int64
roof_type                                   Int64
ground_floor_type                           Int64
other_floor_type                            Int64
position                                    Int64
plan_configuration                          Int64
has_superstructure_adobe_mud                int64
has_superstructure_mud_mortar_stone         int64
has_superstructure_stone_flag               int64
has_superstructure_cement_mortar_stone      int64
has_superstructure_mud_mortar_brick         int64
has_superstructure_cement_mortar_brick      int64
has_superstructure_timber                   int64


In [61]:
corr = training_data.corr()
corr.style.background_gradient(cmap='coolwarm', axis=None)

In [69]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260601 entries, 0 to 260600
Data columns (total 34 columns):
 #   Column                                  Non-Null Count   Dtype  
---  ------                                  --------------   -----  
 0   geo_level_1_id                          260601 non-null  float64
 1   geo_level_2_id                          260601 non-null  float64
 2   count_floors_pre_eq                     260601 non-null  float64
 3   age                                     260601 non-null  float64
 4   area_percentage                         260601 non-null  float64
 5   height_percentage                       260601 non-null  float64
 6   land_surface_condition                  260601 non-null  Int64  
 7   foundation_type                         260601 non-null  Int64  
 8   roof_type                               260601 non-null  Int64  
 9   ground_floor_type                       260601 non-null  Int64  
 10  other_floor_type                        2606

In [92]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

X = training_data.drop('damage_grade', axis=1)
y = training_data['damage_grade']

y = to_categorical(y)
print(y)

random_state = 42
batch_size = 250
validation_split = 0.2

X_train, X_test, y_train, y_test = train_test_split(np.asarray(X).astype('float32'), y, test_size=0.33, random_state=random_state)



[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [101]:
n_epochs = 500
# Create the model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(32, activation='relu', input_dim=33))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(512, activation='relu'))
model.add(tf.keras.layers.Dense(8, activation='relu'))
model.add(tf.keras.layers.Dense(4, activation='sigmoid'))

model.summary()


# Compile the model
model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3, momentum=0.9),
              metrics=['accuracy'])

# Fit data to model
history = model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=n_epochs,
          validation_split=validation_split)

# model.compile(loss = 'categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# history = model.fit(train_generator, epochs=25, steps_per_epoch=20, validation_data = validation_generator, verbose = 1, validation_steps=3)

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_82 (Dense)             (None, 32)                1088      
_________________________________________________________________
dense_83 (Dense)             (None, 128)               4224      
_________________________________________________________________
dense_84 (Dense)             (None, 512)               66048     
_________________________________________________________________
dense_85 (Dense)             (None, 8)                 4104      
_________________________________________________________________
dense_86 (Dense)             (None, 4)                 36        
Total params: 75,500
Trainable params: 75,500
Non-trainable params: 0
_________________________________________________________________
Epoch 1/500
559/559 [==============================] - 3s 5ms/step - loss: 0.9342 - accuracy: 0.5669 - val_loss: 0.

|lr|epochs|acc|val_Acc|conver epoch|momentum|
|---|---|---|---|---|---|
|1e-6|5|0.5685|0.5706|4|0.9|
|1e-3|100|0.6371|0.6365|100|0.9|
|1e-3|500|0.6881|0.6731|500|0.9|

In [106]:
n_epochs = 800
# Create the model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(32, activation='relu', input_dim=33))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(512, activation='relu'))
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(4, activation='sigmoid'))

model.summary()


# Compile the model
model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3, momentum=0.9),
              metrics=['accuracy'])

# Fit data to model
history = model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=n_epochs,
          validation_split=validation_split)

# model.compile(loss = 'categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# history = model.fit(train_generator, epochs=25, steps_per_epoch=20, validation_data = validation_generator, verbose = 1, validation_steps=3)

Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_99 (Dense)             (None, 32)                1088      
_________________________________________________________________
dense_100 (Dense)            (None, 128)               4224      
_________________________________________________________________
dense_101 (Dense)            (None, 512)               66048     
_________________________________________________________________
dense_102 (Dense)            (None, 256)               131328    
_________________________________________________________________
dense_103 (Dense)            (None, 128)               32896     
_________________________________________________________________
dense_104 (Dense)            (None, 4)                 516       
Total params: 236,100
Trainable params: 236,100
Non-trainable params: 0
_______________________________________________

|lr|epochs|acc|val_Acc|conver epoch|momentum|
|---|---|---|---|---|---|
|1e-3|100|0.6499|0.6470|100|0.9|
|1e-3|500|0.7044|0.6780|100|0.9|
|1e-3|800|0.7232|0.6746|100|0.9|

In [114]:
selected_features = ['foundation_type', 
                     'area_percentage', 
                     'height_percentage',
                     'count_floors_pre_eq',
                     'land_surface_condition',
                     'has_superstructure_cement_mortar_stone']
X2 = X[selected_features]
X2.info()
X_train, X_test, y_train, y_test = train_test_split(np.asarray(X2).astype('float32'), y, test_size=0.33, random_state=random_state)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260601 entries, 0 to 260600
Data columns (total 6 columns):
 #   Column                                  Non-Null Count   Dtype  
---  ------                                  --------------   -----  
 0   foundation_type                         260601 non-null  Int64  
 1   area_percentage                         260601 non-null  float64
 2   height_percentage                       260601 non-null  float64
 3   count_floors_pre_eq                     260601 non-null  float64
 4   land_surface_condition                  260601 non-null  Int64  
 5   has_superstructure_cement_mortar_stone  260601 non-null  int64  
dtypes: Int64(2), float64(3), int64(1)
memory usage: 24.4 MB


In [119]:
n_epochs = 100
# Create the model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(32, activation='relu', input_dim=6))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(512, activation='relu'))
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(4, activation='sigmoid'))

model.summary()


# Compile the model
model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer=tf.keras.optimizers.SGD(learning_rate=1e-1, momentum=0.6),
              metrics=['accuracy'])

# Fit data to model
history = model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=n_epochs,
          validation_split=validation_split)

# model.compile(loss = 'categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# history = model.fit(train_generator, epochs=25, steps_per_epoch=20, validation_data = validation_generator, verbose = 1, validation_steps=3)

Model: "sequential_29"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_141 (Dense)            (None, 32)                224       
_________________________________________________________________
dense_142 (Dense)            (None, 128)               4224      
_________________________________________________________________
dense_143 (Dense)            (None, 512)               66048     
_________________________________________________________________
dense_144 (Dense)            (None, 256)               131328    
_________________________________________________________________
dense_145 (Dense)            (None, 128)               32896     
_________________________________________________________________
dense_146 (Dense)            (None, 4)                 516       
Total params: 235,236
Trainable params: 235,236
Non-trainable params: 0
_______________________________________________

KeyboardInterrupt: ignored